version: '3.6'

services:
  frontend:
    image: dorinelfilip/sprcweb
    environment:
      VIRTUAL_HOST: 'sprc.dfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'sprc.dfilip.xyz'
      LETSENCRYPT_EMAIL: 'contact@dfilip.xyz'
    networks:
     - proxy_net

# volumes:
#   example_data:
networks:
  proxy_net:
    external: true

# secrets:
#   example_password:
#     external: true
