version: '3.6'

services:
  frontend:
    image: bitnami/dokuwiki:latest
    environment:
      VIRTUAL_HOST: 'wiki.do1.dfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'wiki.do1.dfilip.xyz'
      LETSENCRYPT_EMAIL: 'contact@dfilip.xyz'
    networks:
     - proxy_net
    volumes:
      - "data:/bitnami"
    environment:
      - "TZ=Europe/Bucharest"

volumes:
  data:
networks:
  proxy_net:
    external: true

# secrets:
#   example_password:
#     external: true
