version: '3.6'

services:
  auth:
    image: dorinelfilip/si-auth
    environment:
      VIRTUAL_HOST: 'auth.si.dorinelfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'auth.si.dorinelfilip.xyz'
      LETSENCRYPT_EMAIL: 'contact@dfilip.xyz'
      auth_frontend: 'auth.si.dorinelfilip.xyz'
      worker_frontend: 'worker.si.dorinelfilip.xyz'
      trudy_frontend: 'trudy.si.dorinelfilip.xyz'
    networks:
     - proxy_net

  worker:
    image: dorinelfilip/si-worker
    environment:
      VIRTUAL_HOST: 'worker.si.dorinelfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'worker.si.dorinelfilip.xyz'
      LETSENCRYPT_EMAIL: 'contact@dfilip.xyz'
      auth_frontend: 'auth.si.dorinelfilip.xyz'
      worker_frontend: 'worker.si.dorinelfilip.xyz'
      trudy_frontend: 'trudy.si.dorinelfilip.xyz'
    networks:
     - proxy_net

  trudy:
    image: dorinelfilip/si-trudy
    environment:
      VIRTUAL_HOST: 'trudy.si.dorinelfilip.xyz'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'trudy.si.dorinelfilip.xyz'
      LETSENCRYPT_EMAIL: 'contact@dfilip.xyz'
      auth_frontend: 'auth.si.dorinelfilip.xyz'
      worker_frontend: 'worker.si.dorinelfilip.xyz'
      trudy_frontend: 'trudy.si.dorinelfilip.xyz'
    networks:
     - proxy_net

# volumes:
#   example_data:
networks:
  proxy_net:
    external: true

# secrets:
#   example_password:
#     external: true