version: '3.6'

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb

  chronograf:
    image: chronograf
    deploy:
      replicas: 0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      VIRTUAL_HOST: 'chronograf.isi.dfilip.xyz'
      VIRTUAL_PORT: 8888
    networks:
      - influxdb
      - proxy_net

  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    networks:
      - influxdb

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: '/run/secrets/grafana_password'
      VIRTUAL_HOST: 'grafana.isi.dfilip.xyz'
      LETSENCRYPT_HOST: 'grafana.isi.dfilip.xyz'
      LETSENCRYPT_EMAIL: 'dorinel.filip@gmail.com'
    networks:
     - influxdb
     - proxy_net
    volumes:
      - grafana:/var/lib/grafana
    secrets:
      - grafana_password

  broker:
    image: dorinelfilip/emqtt
    volumes:
      - emqtt_data:/opt/emqttd/data
      - emqtt_etc:/opt/emqttd/etc
      - emqtt_lib:/opt/emqttd/lib
      - emqtt_log:/opt/emqttd/log
    ports:
     - "1883:1883"
    environment:
      EMQ_LOADED_PLUGINS: 'emq_recon,emq_modules,emq_retainer'
    networks:
     - broker
     - proxy_net

  mqtt2influxdb:
    image: dorinelfilip/mqtt-to-graphite
    environment:
      - CARBON_SERVER=influxdb
      # - CARBON_PORT=2003
      - MQTT_HOST=broker
      # -MQTT_PORT=1883
    networks:
     - broker
     - influxdb


volumes:
  emqtt_data:
  emqtt_etc:
  emqtt_lib:
  emqtt_log:
  grafana:
  iot-data:
  influxdb:
networks:
  graphite:
  broker:
  influxdb:
  proxy_net:
    external: true
secrets:
  grafana_password:
    external: true
